language: java
jdk: oraclejdk11
dist: trusty
install: true
sudo: required
addons:
  chrome: stable
  sonarcloud:
    organization: "markoniemi-github"
    token: $SONAR_CLOUD_TOKEN
script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package verify
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'